# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
kotlinVersion=2.4.20
archivesName=DimOre

# Mod data
mod.id=dimore
mod.name=Dimensional Ores
mod.version=1.6.0
mod.group=com.algorithmlx
mod.description=Add ores to your dimensions!

# Dependencies
mod.depend.flk_version=1.14.1
mod.depend.klf_loader_version=3.1
mod.depend.klf_version=2.14.1

# Publish projects
publish.modrinth.project_id=tdrqr7qS
publish.modrinth.fabric.depends=fabric-api,fabric-language-kotlin
publish.modrinth.neoforge.depends=kotlin-lang-forge

publish.curseforge.project_id=548552
publish.curseforge.fabric.depends=fabric-api,fabric-language-kotlin
publish.curseforge.neoforge.depends=kotlinlangforge

publish.github.project_id=AlgorithmLX/DimOre
publish.github.branch=stonecutter
