mod.platforms=fabric,neoforge
build.ignore=false
build.release_type=beta
build.no_publish=true

minecraft_version=26.2
minecraft_version.additional=
loader_version=0.19.3

fabric_version=0.152.2+26.2

neoforge_version=26.2.0.3-beta
