mod.platforms=fabric,neoforge
build.ignore=false
build.release_type=beta
build.no_publish=false

minecraft_version=26.3
minecraft_version.additional=
loader_version=0.19.5

fabric_version=0.160.7+26.3

neoforge_version=26.3.0.4-beta
